application: your-app-id-here
version: your-version-here
runtime: python27
api_version: 1
threadsafe: true

builtins:
- appstats: on
- remote_api: on

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"

inbound_services:
- warmup

handlers:
- url: /admin(/.*)?
  script: google.appengine.ext.admin.application
  login: admin

- url: /static
  static_dir: dpxdt/server/static

- url: .*
  script: dpxdt.server.app
